name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
        - uses: actions/checkout@v4
          with:
            submodules: recursive
    
        # Used to host cibuildwheel
        - uses: actions/setup-python@v3
    
        - name: Install cibuildwheel
          run: python -m pip install cibuildwheel==2.16.2

        - name: Build wheels
          run: python -m cibuildwheel --output-dir wheelhouse
            # to supply options, put them in 'env', like:
            # env:
            #   CIBW_SOME_OPTION: value
          env:
            CIBW_BEFORE_BUILD: git submodule update --init --recursive && pip install .
    
        - uses: actions/upload-artifact@v3
          with:
            path: ./wheelhouse/*.whl